<template>
  <article
    className="prose prose-base dark:prose-invert prose-neutral mt-20 mx-5 md:mx-10 mb-[20vh]"
  >
    <header id="title-block-header">
      <h1 class="title">Follow Language-Quick Start</h1>
    </header>
    <p>
      <code>Follow</code> is a language for mathematical formal proof. The
      mathematical proofs written by nature language are always ambiguous and
      error-prone, so we need teacher to clean up confusion and check proof.
      <code>Follow</code> is designed to solve these two problems by using
      computer.
    </p>
    <p>
      <code>Follow</code> only has 9 keywords: <code>type</code>,
      <code>const</code>, <code>prop</code>, <code>axiom</code>,
      <code>thm</code>, <code>absurd</code>, <code>|-</code>, <code>-|</code>,
      <code>|-|</code>. So it is very easy to learn. If you are looking for some
      tool to help yourself studying mathematics, <code>Follow</code> is a good
      choice.
    </p>
    <h2 id="keyword-type">1. Keyword <code>type</code></h2>
    <h3 id="syntax">1.1 syntax</h3>
    <pre class="follow"><code>type &lt;TYPENAME&gt;</code></pre>
    <h3 id="examples">1.2 examples</h3>
    <pre class="follow"><code>type set
type wff // (well-formed-formula)</code></pre>
    <h2 id="keyword-const">2. Keyword <code>const</code></h2>
    <h3 id="syntax-1">2.1 syntax</h3>
    <pre
      class="follow"
    ><code>const &lt;TYPENAME&gt; &lt;CONSTNAME&gt;</code></pre>
    <h3 id="examples-1">2.2 examples</h3>
    <pre class="follow"><code>const set emptyset
const wff true
const wff false</code></pre>
    <h2 id="keyword-prop">3. Keyword <code>prop</code></h2>
    <h3 id="syntax-2">3.1 syntax</h3>
    <pre
      class="follow"
    ><code>prop &lt;TYPENAME&gt; &lt;PROPNAME&gt;(&lt;TYPENAME&gt; &lt;ARGNAME&gt;, &lt;TYPENAME&gt; &lt;ARGNAME&gt;, ...)</code></pre>
    <h3 id="examples-2">3.2 examples</h3>
    <pre class="follow"><code>prop set in(set s0, set s1)
prop wff imply(wff w0, wff w1)</code></pre>
    <h2 id="keyword-axiom-with-keywords---and--">
      4. Keyword <code>axiom</code> (with keywords <code>|-</code> and
      <code>-|</code>)
    </h2>
    <h3 id="syntax-3">4.1 syntax</h3>
    <pre
      class="follow"
    ><code>axiom &lt;AXIOMNAME&gt; (&lt;TYPENAME&gt; &lt;ARGNAME&gt;, &lt;TYPENAME&gt; &lt;ARGNAME&gt;, ...) {
    |- &lt;conclusion-statement&gt;
    -| &lt;condition-statement&gt;
    -| &lt;condition-statement&gt;
    ...
}</code></pre>
    <p>
      <code>|-</code> means conclusion, <code>-|</code> means condition. Every
      block generated by <code>axiom</code> is true in <code>Follow</code>.
    </p>
    <h3 id="examples-3">4.2 examples</h3>
    <pre class="follow"><code>axiom ax-true() { |- true }
axiom ax-mp(wff w0, wff w1) { 
    |- w0 
    -| imply(w1, w0) 
    -| w1 
}</code></pre>
    <h2 id="keyword-thm">5. Keyword <code>thm</code></h2>
    <h3 id="syntax-4">5.1 syntax</h3>
    <pre
      class="follow"
    ><code>thm &lt;THMNAME&gt; (&lt;TYPENAME&gt; &lt;ARGNAME&gt;, &lt;TYPENAME&gt; &lt;ARGNAME&gt;, ...) {
    |- &lt;conclusion-statement&gt;
    -| &lt;condition-statement&gt;
    -| &lt;condition-statement&gt;
    ...
} = {
    &lt;proof-statement&gt;
    &lt;proof-statement&gt;
    &lt;proof-statement&gt;
    ...
}</code></pre>
    <h3 id="examples-4">5.2 examples</h3>
    <pre class="thm"><code>thm mp2(wff w0, wff w1, wff w2) { 
    ⊢ w0 
    ⊣ w1 
    ⊣ w2 
    ⊣ imply(w1, imply(w2, w0))
} = { 
    ax-mp(w0, w2) 
    ax-mp(imply(w2, w0), w1) 
}</code></pre>
    <p>Here is some explaination:</p>
    <p><code>ax-mp(w0, w2)</code> generates a conclusion-condition block</p>
    <pre class="follow"><code>|- w0 
-| imply(w2, w0)
-| w2</code></pre>
    <p>
      <code>ax-mp(imply(w2, w0), w1)</code> generates a conclusion-condition
      block
    </p>
    <pre class="follow"><code>|- imply(w2, w0)
-| imply(w1, imply(w2, w0))
-| w1</code></pre>
    <p>
      Notice that <code>imply(w2, w0)</code> is the condition of first block and
      is also the conclusion of second block, so it is cancelled. Join the two
      blocks will get a new block,
    </p>
    <pre class="follow"><code>|- w0
-| w2 
-| w1
-| imply(w1, imply(w2, w0))</code></pre>
    <p>
      which is exactly the target of the theorem <code>mp2</code>. In
      <code>Follow</code> Language, we call <code>mp2</code> is proved.
    </p>
    <h2 id="keyword-absurd-with-keyword--">
      6. Keyword <code>absurd</code> (with keyword <code>|-|</code>)
    </h2>
    <h3 id="syntax-5">6.1 syntax</h3>
    <pre
      class="follow"
    ><code>absurd &lt;ABSURDNAME&gt;(&lt;TYPENAME&gt; &lt;ARGNAME&gt;, &lt;TYPENAME&gt; &lt;ARGNAME&gt;, ...) {
    |-| &lt;absurd-statement&gt;
}</code></pre>
    <p>
      Every block generated by <code>absurd</code> is false in
      <code>Follow</code>. If a proof statement generates a statement can be
      generated by absurd, <code>Follow</code> will immediately label proof
      wrong.
    </p>
    <h3 id="examples-5">6.2 examples</h3>
    <pre class="follow"><code>absurd absurd-false() { |-| false }
absurd absurd-imply) {
    |-| imply(true, false)
}</code></pre>
  </article>
</template>
